// Node tests for the practice shell (src/shell.js): the file system, the parser, every command's output and error text, the limits,
// and what a hostile saved copy can and cannot do.  node test_shell.js
const SHELL = require('./src/shell.js');
let bad = 0;
const check = (name, got, want) => { const ok = want instanceof RegExp ? want.test(got) : got === want; if (!ok) { bad++; console.log('BAD  ' + name + '\n  got:  ' + JSON.stringify(got) + '\n  want: ' + (want instanceof RegExp ? want : JSON.stringify(want))); } };
const T0 = Date.UTC(2026, 9, 1, 14, 0, 0);
function fresh(hooks) {
  const fs = SHELL.makeFS(null, { now: () => T0 });
  const sh = SHELL.makeShell(Object.assign({ fs, now: fs.now,
    run: async (lang, src, o) => { o.onOutput(lang + ':' + src.trim() + (o.stdin == null ? '' : '<' + JSON.stringify(o.stdin)) + (o.args.length ? ' ' + o.args.join(',') : '') + '\n'); return /boom/.test(src) ? { err: 'Error: boom', exit: 1 } : { err: null, exit: 0 }; },
    compile: async (lang, src, o) => /bad/.test(src) ? { err: o.name + ':1:1: error: bad' } : { err: null } }, hooks || {}));
  const asks = [];
  const run = async (line, io) => { let out = ''; const exit = await sh.exec(line, Object.assign({ out: (s) => { out += s; }, err: (s) => { out += s; }, tty: true, ask: async (p) => { asks.push(p); return asks.length > 20 ? '' : 'typed'; } }, io || {})); return { out, exit }; };
  return { fs, sh, run, asks };
}
const eq = (name, r, out, exit) => { check(name + ' output', r.out, out); if (exit !== undefined) check(name + ' exit', r.exit, exit); };

(async () => {
  // ---- the file system
  {
    const { fs } = fresh();
    check('home exists', fs.isDir('/home/student'), true);
    check('resolve ..', fs.resolve('../x', '/home/student'), '/home/x');
    check('resolve ~', fs.resolve('~/a/./b//c/..'), '/home/student/a/b');
    check('resolve above root', fs.resolve('/../../etc'), '/etc');
    fs.mkdir('/home/student/d'); fs.write('/home/student/d/f.txt', 'hi');
    check('read', fs.read('/home/student/d/f.txt'), 'hi');
    fs.write('/home/student/d/f.txt', ' there', true); check('append', fs.read('/home/student/d/f.txt'), 'hi there');
    let e = null; try { fs.write('/etc/x', 'no'); } catch (x) { e = x.code; } check('system is read-only', e, 'EACCES');
    e = null; try { fs.unlink('/bin/ls'); } catch (x) { e = x.code; } check('cannot remove a command', e, 'EACCES');
    e = null; try { fs.mkdir('/home/student/d'); } catch (x) { e = x.code; } check('mkdir exists', e, 'EEXIST');
    e = null; try { fs.read('/home/student/d'); } catch (x) { e = x.code; } check('read a dir', e, 'EISDIR');
    e = null; try { fs.write('/home/student/nope/f', ''); } catch (x) { e = x.code; } check('missing parent', e, 'ENOENT');
    e = null; try { fs.write('/home/student/d/f.txt/g', ''); } catch (x) { e = x.code; } check('file as parent', e, 'ENOTDIR');
    e = null; try { fs.mkdir('/home/student/' + 'x'.repeat(101)); } catch (x) { e = x.code; } check('long name', e, 'ENAMETOOLONG');
    e = null; try { fs.write('/home/student/big', 'x'.repeat(SHELL.LIMITS.fileBytes + 1)); } catch (x) { e = x.code; } check('file too big', e, 'EFBIG');
    e = null; try { fs.copy('/home/student/d', '/home/student/d/inside', true); } catch (x) { e = x.code; } check('copy into itself', e, 'EINVAL');
    fs.move('/home/student/d', '/home/student/e'); check('move', fs.read('/home/student/e/f.txt'), 'hi there');
    fs.cwd = '/home/student/e'; fs.move('/home/student/e', '/home/student/g'); check('cwd follows a moved dir', fs.cwd, '/home/student/g');
    const saved = JSON.parse(JSON.stringify(fs.toJSON()));
    check('only home and tmp are saved', saved.root.c.map((e) => e[0]).join(','), 'home,tmp');
    const fs2 = SHELL.makeFS(saved, { now: () => T0 });
    check('round trip', fs2.read('/home/student/g/f.txt'), 'hi there'); check('round trip cwd', fs2.cwd, '/home/student/g'); check('system rebuilt', fs2.isFile('/bin/ls'), true);
    // hostile saved copies
    const h = SHELL.makeFS({ v: 1, cwd: '/etc', root: { t: 'd', c: [['home', { t: 'd', c: [['student', { t: 'd', c: [['__proto__', { t: 'f', d: 'p' }], ['constructor', { t: 'd', c: [] }], ['a/b', { t: 'f', d: 'y' }], ['..', { t: 'd', c: [] }], ['', { t: 'f', d: '' }], ['ctl\u0001', { t: 'f', d: '' }], ['big', { t: 'f', d: 'x'.repeat(SHELL.LIMITS.fileBytes + 1) }], ['ok', { t: 'f', d: 'z', x: 'yes', bin: { lang: 'c++', src: 'int main(){}', std: 'bad std' } }], ['ok2', { t: 'f', d: '', bin: { lang: 'cpp', src: 's', std: 'gnu++20' } }], ['n', { t: 'f', d: 42 }], ['weird', { t: 'x' }]] }]] }], ['bin', { t: 'd', c: [['ls', { t: 'f', d: 'evil', x: true }]] }], ['etc', { t: 'd', c: [['passwd', { t: 'f', d: 'hacked' }]] }]] } }, { now: () => T0 });
    check('hostile: names kept only when valid', h.list('/home/student').join(','), 'constructor,ok,ok2,__proto__');
    check('hostile: dictionaries have no prototype', Object.getPrototypeOf(h.stat('/home/student').c), null);
    check('hostile: __proto__ is just a file', h.read('/home/student/__proto__'), 'p');
    check('hostile: exec bit must be true', h.stat('/home/student/ok').x, false);
    check('hostile: bad bin dropped', h.stat('/home/student/ok').bin, undefined);
    check('hostile: good bin kept, std checked', h.stat('/home/student/ok2').bin.std, 'gnu++20');
    check('hostile: system not replaced', h.read('/etc/passwd').startsWith('root:'), true);
    check('hostile: /bin not replaced', h.stat('/bin/ls').d, '');
    check('hostile: cwd checked', h.cwd, '/etc');
    const deep = (n) => n === 0 ? { t: 'd', c: [] } : { t: 'd', c: [['d', deep(n - 1)]] };
    const dfs = SHELL.makeFS({ v: 1, root: { t: 'd', c: [['home', { t: 'd', c: [['student', deep(60)]] }]] } }, { now: () => T0 });
    check('hostile: depth capped', dfs.walk('/home').length <= SHELL.LIMITS.depth + 2, true);
    const many = { t: 'd', c: [] }; for (let i = 0; i < 700; i++) many.c.push(['f' + i, { t: 'f', d: 'x' }]);
    const mfs = SHELL.makeFS({ v: 1, root: { t: 'd', c: [['home', { t: 'd', c: [['student', many]] }]] } }, { now: () => T0 });
    check('hostile: file count capped', mfs.usage().files, SHELL.LIMITS.files);
    check('garbage saved copy', SHELL.makeFS('nonsense', { now: () => T0 }).cwd, '/home/student');
    check('garbage saved copy 2', SHELL.makeFS({ root: 5 }, { now: () => T0 }).isDir('/home/student'), true);
  }

  // ---- the parser
  {
    const w = (line) => SHELL.parse(line).items[0].first.cmds[0].words.map((x) => x.parts);
    check('quotes', JSON.stringify(w('echo "a b" \'c $d\' e\\ f')), JSON.stringify([[{ v: 'echo', q: false }], [{ v: 'a b', q: true }], [{ v: 'c $d', q: true }], [{ v: 'e', q: false }, { v: ' ', q: true }, { v: 'f', q: false }]]));
    check('variables', JSON.stringify(w('echo $x ${y}z "$?"')[1]), JSON.stringify([{ x: 'var', v: 'x', q: false }]));
    check('variables 2', JSON.stringify(w('echo $x ${y}z "$?"')[2]), JSON.stringify([{ x: 'var', v: 'y', q: false }, { v: 'z', q: false }]));
    check('variables 3', JSON.stringify(w('echo $x ${y}z "$?"')[3]), JSON.stringify([{ x: 'var', v: '?', q: true }]));
    check('substitution', JSON.stringify(w('echo $(ls -l | wc) $((1+2))')[1]), JSON.stringify([{ x: 'sub', v: 'ls -l | wc', q: false }]));
    check('arith', JSON.stringify(w('echo $(ls -l | wc) $((1+2))')[2]), JSON.stringify([{ x: 'arith', v: '1+2', q: false }]));
    check('backslash in double quotes keeps \\n', JSON.stringify(w('printf "a\\nb"')[1]), JSON.stringify([{ v: 'a', q: true }, { v: '\\', q: true }, { v: 'nb', q: true }]));
    check('comment', w('echo a # not this').length, 2);
    check('empty quotes are a word', w('echo "" x').length, 3);
    const p = SHELL.parse('a | b && c || d; e');
    check('list', p.items.length, 2); check('andor', p.items[0].rest.map((r) => r.op).join(), '&&,||'); check('pipe', p.items[0].first.cmds.length, 2);
    const r = SHELL.parse('cat < in > out 2>> err 2>&1').items[0].first.cmds[0].redirs.map((x) => x.op);
    check('redirs', r.join(), '<,>,2>>,2>&1');
    check('assign', JSON.stringify(SHELL.parse('X=1 Y="a b" cmd').items[0].first.cmds[0].assigns.map((a) => a[0])), '["X","Y"]');
    check('if', SHELL.parse('if true; then echo a; elif false; then echo b; else echo c; fi').items[0].first.cmds[0].k, 'if');
    check('for', SHELL.parse('for x in a b; do echo $x; done').items[0].first.cmds[0].name, 'x');
    check('for over args', SHELL.parse('for x\ndo echo $x\ndone').items[0].first.cmds[0].words, null);
    check('while', SHELL.parse('while [ 1 ]; do :; done | cat').items[0].first.cmds.length, 2);
    check('multi-line', SHELL.parse('a\nb\n\nc').items.length, 3);
    for (const [line, msg] of [['echo "x', /matching `"'/], ["echo 'x", /matching `''/], ['ls |', /unexpected token `end of line'/], ['| ls', /unexpected token `\|'/], ['echo $(ls', /matching `\)'/], ['if true; then echo', /expected fi/], ['for in; do; done', /for needs a variable name/], ['ls &', /background jobs/], ['fi', /unexpected token `fi'/], ['echo a;; b', /`;;'/], ['echo ${x', /matching `}'/]]) {
      let got = ''; try { SHELL.parse(line); } catch (e) { got = e.message; } check('syntax error: ' + line, got, msg);
    }
    check('arith ops', [SHELL.arith('1 + 2 * 3', () => ''), SHELL.arith('(1 + 2) * 3', () => ''), SHELL.arith('7 / 2', () => ''), SHELL.arith('-7 % 3', () => ''), SHELL.arith('2 ** 3 ** 2', () => ''), SHELL.arith('3 > 2 && 1', () => ''), SHELL.arith('x + 1', (n) => n === 'x' ? '41' : '')].join(), '7,9,3,-1,512,1,42');
    check('brace', SHELL.braceExpand('f{1..3}.{txt,md}').join(' '), 'f1.txt f1.md f2.txt f2.md f3.txt f3.md');
    check('brace reversed', SHELL.braceExpand('{3..1}').join(' '), '3 2 1');
    check('brace huge is left alone', SHELL.braceExpand('{1..999999}').join(' '), '{1..999999}');
    check('glob regexp', [SHELL.globToRegExp('*.txt').test('a.txt'), SHELL.globToRegExp('*.txt').test('a/b.txt'), SHELL.globToRegExp('?.py').test('ab.py'), SHELL.globToRegExp('[a-c]*').test('b1'), SHELL.globToRegExp('[!a]x').test('ax'), SHELL.globToRegExp('\\*x').test('*x'), SHELL.globToRegExp('\\*x').test('ax')].join(), 'true,false,false,true,false,true,false');
  }

  // ---- commands: output and error text
  {
    const { fs, sh, run } = fresh();
    eq('pwd', await run('pwd'), '/home/student\n', 0);
    eq('prompt', { out: sh.prompt(), exit: 0 }, 'student@lab:~$ ');
    eq('mkdir + ls', await run('mkdir notes projects; ls'), 'notes  projects\n', 0);
    eq('cd + prompt', { out: (await run('cd notes')).out + sh.prompt(), exit: 0 }, 'student@lab:~/notes$ ');
    eq('cd missing', await run('cd nowhere'), 'bash: cd: nowhere: No such file or directory\n', 1);
    eq('cd file', await run('echo x > f.txt; cd f.txt'), 'bash: cd: f.txt: Not a directory\n', 1);
    eq('cd too many', await run('cd a b'), 'bash: cd: too many arguments\n', 1);
    eq('cd ..', await run('cd ..; pwd'), '/home/student\n');
    eq('cd -', await run('cd notes; cd -; pwd'), '/home/student\n/home/student\n');
    eq('cd home', await run('cd /tmp; cd; pwd'), '/home/student\n');
    eq('ls missing', await run('ls nope'), "ls: cannot access 'nope': No such file or directory\n", 2);
    eq('ls -a', await run('ls -a notes'), '.  ..  f.txt\n');
    eq('ls several', await run('ls notes projects'), 'notes:\nf.txt\n\nprojects:\n');
    eq('ls -F', await run('ls -F'), 'notes/  projects/\n');
    eq('ls -d', await run('ls -d notes'), 'notes\n');
    eq('ls -l', await run('ls -l notes'), /^total 4\n-rw-r--r-- 1 student student 2 Oct  1 \d\d:\d\d f\.txt\n$/);
    eq('ls dir in pipe: one per line', await run('ls | cat'), 'notes\nprojects\n');
    eq('ls order', await run('cd /tmp; touch b.txt A.txt _c.txt a.txt; ls; cd; rm /tmp/*.txt'), 'a.txt  A.txt  b.txt  _c.txt\n');
    eq('ls order ignores punctuation like a terminal', await run('cd /tmp; touch ab.txt abc.txt a_d.txt; ls; cd; rm /tmp/*.txt'), 'abc.txt  ab.txt  a_d.txt\n');
    eq('ls bad option', await run('ls -z'), "ls: invalid option -- 'z'\nTry 'man ls' for help.\n", 2);
    eq('mkdir exists', await run('mkdir notes'), "mkdir: cannot create directory 'notes': File exists\n", 1);
    eq('mkdir missing parent', await run('mkdir a/b/c'), "mkdir: cannot create directory 'a/b/c': No such file or directory\n", 1);
    eq('mkdir -p', await run('mkdir -p a/b/c; mkdir -p a/b/c; find a'), 'a\na/b\na/b/c\n', 0);
    eq('mkdir braces', await run('mkdir {x,y,z}; ls -d x y z; rmdir x y z'), 'x  y  z\n');
    eq('rmdir not empty', await run('rmdir a'), "rmdir: failed to remove 'a': Directory not empty\n", 1);
    eq('touch and echo >', await run('touch t.txt; echo hello > h.txt; cat t.txt h.txt'), 'hello\n');
    eq('touch missing dir', await run('touch nope/x'), "touch: cannot touch 'nope/x': No such file or directory\n", 1);
    eq('cat missing', await run('cat nope'), 'cat: nope: No such file or directory\n', 1);
    eq('cat dir', await run('cat notes'), 'cat: notes: Is a directory\n', 1);
    eq('cat -n', await run('printf "a\\nb\\n" > ab.txt; cat -n ab.txt'), '     1\ta\n     2\tb\n');
    eq('cat several and >', await run('cat ab.txt h.txt > all.txt; cat all.txt'), 'a\nb\nhello\n');
    eq('>> appends', await run('echo more >> h.txt; cat h.txt'), 'hello\nmore\n');
    eq('> truncates first', await run('cat h.txt > h.txt; wc -c h.txt'), '0 h.txt\n');
    eq('> into missing dir', await run('echo x > nope/f'), 'bash: nope/f: No such file or directory\n', 1);
    eq('> onto a dir', await run('echo x > notes'), 'bash: notes: Is a directory\n', 1);
    eq('> system', await run('echo x > /etc/passwd; cat /etc/hostname'), 'bash: /etc/passwd: Permission denied\nlab\n');
    eq('< file', await run('wc -l < ab.txt'), '2\n');
    eq('< missing', await run('cat < nope'), 'bash: nope: No such file or directory\n', 1);
    eq('2>', await run('ls nope 2> err.txt; cat err.txt'), "ls: cannot access 'nope': No such file or directory\n");
    eq('2>&1 |', await run('ls nope 2>&1 | wc -l'), '1\n');
    eq('/dev/null', await run('ls nope 2>/dev/null; echo $?'), '2\n');
    eq('cp', await run('cp ab.txt copy.txt; cat copy.txt'), 'a\nb\n');
    eq('cp into dir', await run('cp ab.txt notes; ls notes'), 'ab.txt  f.txt\n');
    eq('cp missing', await run('cp nope x'), "cp: cannot stat 'nope': No such file or directory\n", 1);
    eq('cp dir without -r', await run('cp notes n2'), "cp: -r not specified; omitting directory 'notes'\n", 1);
    eq('cp -r', await run('cp -r notes n2; ls n2'), 'ab.txt  f.txt\n');
    eq('cp many to file', await run('cp ab.txt h.txt copy.txt'), "cp: target 'copy.txt' is not a directory\n", 1);
    eq('cp one arg', await run('cp ab.txt'), "cp: missing destination file operand after 'ab.txt'\n", 1);
    eq('mv rename', await run('mv copy.txt renamed.txt; ls renamed.txt copy.txt'), "ls: cannot access 'copy.txt': No such file or directory\nrenamed.txt\n", 2);
    eq('mv into dir', await run('mv renamed.txt projects/; ls projects'), 'renamed.txt\n');
    eq('mv missing', await run('mv nope x'), "mv: cannot stat 'nope': No such file or directory\n", 1);
    eq('mv dir', await run('mv n2 n3; ls -d n3'), 'n3\n');
    eq('rm', await run('rm t.txt; ls t.txt'), "ls: cannot access 't.txt': No such file or directory\n", 2);
    eq('rm missing', await run('rm nope'), "rm: cannot remove 'nope': No such file or directory\n", 1);
    eq('rm -f missing', await run('rm -f nope'), '', 0);
    eq('rm dir', await run('rm n3'), "rm: cannot remove 'n3': Is a directory\n", 1);
    eq('rm -r', await run('rm -r n3; ls -d n3'), "ls: cannot access 'n3': No such file or directory\n", 2);
    eq('rm -r home refused', await run('rm -rf ~'), "rm: refusing to remove '/home/student': it is your home directory\n", 1);
    eq('rm system', await run('rm /bin/ls'), "rm: cannot remove '/bin/ls': Permission denied\n", 1);
    eq('rm wildcard', await run('touch x1.tmp x2.tmp; rm *.tmp; ls *.tmp'), "ls: cannot access '*.tmp': No such file or directory\n", 2);
    eq('wildcard no match stays literal', await run('echo *.zzz'), '*.zzz\n');
    eq('wildcard quoted', await run('echo "*.txt" \'*.txt\''), '*.txt *.txt\n');
    eq('wildcard', await run('echo *.txt'), 'ab.txt all.txt err.txt h.txt\n');
    eq('wildcard ?', await run('echo ?.txt'), 'h.txt\n');
    eq('wildcard in dirs', await run('echo */*.txt'), 'notes/ab.txt notes/f.txt projects/renamed.txt\n');
    eq('wildcard hides dotfiles', await run('touch .secret; echo *; echo .s*; rm .secret'), 'a ab.txt all.txt err.txt h.txt notes projects\n.secret\n');
    eq('tilde', await run('echo ~ ~/x; echo "~"'), '/home/student /home/student/x\n~\n');
    eq('head', await run('seq 20 | head -3'), '1\n2\n3\n');
    eq('head -n', await run('seq 20 | head -n 2'), '1\n2\n');
    eq('tail', await run('seq 20 | tail -2'), '19\n20\n');
    eq('head missing', await run('head nope'), 'head: nope: No such file or directory\n', 1);
    eq('head two files', await run('head -1 ab.txt h.txt'), '==> ab.txt <==\na\n\n==> h.txt <==\n');
    eq('wc', await run('printf "one two\\nthree\\n" > w.txt; wc w.txt'), ' 2  3 14 w.txt\n');
    eq('wc -l pipe', await run('cat w.txt | wc -l'), '2\n');
    eq('wc several', await run('wc -l w.txt ab.txt'), '2 w.txt\n2 ab.txt\n4 total\n');
    eq('wc missing', await run('wc nope'), 'wc: nope: No such file or directory\n', 1);
    eq('grep', await run('grep t w.txt'), 'one two\nthree\n', 0);
    eq('grep -n', await run('grep -n three w.txt'), '2:three\n');
    eq('grep -i -c', await run('grep -ic T w.txt'), '2\n');
    eq('grep -v', await run('grep -v one w.txt'), 'three\n');
    eq('grep -w', await run('grep -w thre w.txt; echo $?'), '1\n');
    eq('grep no match exit', await run('grep zzz w.txt'), '', 1);
    eq('grep -q', await run('if grep -q one w.txt; then echo found; fi'), 'found\n');
    eq('grep missing', await run('grep x nope'), 'grep: nope: No such file or directory\n', 2);
    eq('grep dir', await run('grep x notes'), 'grep: notes: Is a directory\n', 2);
    eq('grep -r', await run('grep -r hello . | sort'), './all.txt:hello\n');
    eq('grep several files prefix', await run('grep a ab.txt all.txt'), 'ab.txt:a\nall.txt:a\n');
    eq('grep -l', await run('grep -l a ab.txt w.txt all.txt'), 'ab.txt\nall.txt\n');
    eq('grep regex', await run('grep "^t" w.txt; grep -F "^t" w.txt; echo $?'), 'three\n1\n');
    eq('grep bad regex is text', await run('echo "a(b" | grep "a("'), 'a(b\n');
    eq('grep no args', await run('grep'), /^Usage: grep/, 2);
    eq('sort', await run('printf "pear\\napple\\nFig\\n" > s.txt; sort s.txt'), 'Fig\napple\npear\n');
    eq('sort -f', await run('sort -f s.txt'), 'apple\nFig\npear\n');
    eq('sort -r', await run('sort -r s.txt'), 'pear\napple\nFig\n');
    eq('sort -n', await run('printf "10\\n9\\n100\\n" | sort -n'), '9\n10\n100\n');
    eq('sort text numbers', await run('printf "10\\n9\\n100\\n" | sort'), '10\n100\n9\n');
    eq('sort -u', await run('printf "b\\na\\nb\\n" | sort -u'), 'a\nb\n');
    eq('sort -k -t', await run('printf "ann,3\\nbob,1\\n" | sort -t , -k 2 -n'), 'bob,1\nann,3\n');
    eq('uniq -c', await run('printf "b\\na\\nb\\nb\\n" | sort | uniq -c'), '      1 a\n      3 b\n');
    eq('uniq -d', await run('printf "a\\na\\nb\\n" | uniq -d'), 'a\n');
    eq('cut -d -f', await run('printf "ann,3,x\\nbob,1,y\\n" | cut -d , -f 1,3'), 'ann,x\nbob,y\n');
    eq('cut -f range', await run('printf "a,b,c,d\\n" | cut -d , -f 2-'), 'b,c,d\n');
    eq('cut -c', await run('echo abcdef | cut -c 2-4'), 'bcd\n');
    eq('cut no delimiter line', await run('printf "a,b\\nplain\\n" | cut -d , -f 2'), 'b\nplain\n');
    eq('cut without list', await run('cut w.txt'), /must specify/, 1);
    eq('tr', await run('echo hello | tr a-z A-Z'), 'HELLO\n');
    eq('tr -d', await run('echo "a,b,c" | tr -d ,'), 'abc\n');
    eq('tr classes', await run('echo "Hi There" | tr "[:upper:]" "[:lower:]"'), 'hi there\n');
    eq('tr -s', await run('echo "a   b" | tr -s " "'), 'a b\n');
    eq('tr newline', await run("echo 'a b' | tr ' ' '\\n'"), 'a\nb\n');
    eq('sed s', await run('echo "colour colour" | sed "s/colour/color/"'), 'color colour\n');
    eq('sed s g', await run('echo "colour colour" | sed "s/colour/color/g"'), 'color color\n');
    eq('sed -i', await run('sed -i "s/one/ONE/" w.txt; cat w.txt'), 'ONE two\nthree\n');
    eq('sed -n p', await run('seq 5 | sed -n 2,3p'), '2\n3\n');
    eq('sed d', await run('seq 3 | sed 2d'), '1\n3\n');
    eq('sed unknown', await run('seq 3 | sed y/a/b/'), /unknown command: 'y'/, 1);
    eq('rev', await run('echo abc | rev'), 'cba\n');
    eq('tac', await run('seq 3 | tac'), '3\n2\n1\n');
    eq('nl', await run('printf "a\\n\\nb\\n" | nl'), '     1\ta\n       \n     2\tb\n');
    eq('diff same', await run('diff ab.txt ab.txt'), '', 0);
    eq('diff', await run('printf "a\\nc\\n" > ac.txt; diff ab.txt ac.txt'), '2c2\n< b\n---\n> c\n', 1);
    eq('diff add', await run('printf "a\\nb\\nc\\n" > abc.txt; diff ab.txt abc.txt'), '2a3\n> c\n', 1);
    eq('diff delete', await run('diff abc.txt ab.txt'), '3d2\n< c\n', 1);
    eq('diff missing', await run('diff ab.txt nope'), 'diff: nope: No such file or directory\n', 2);
    eq('tee', await run('echo both | tee t.txt; cat t.txt'), 'both\nboth\n');
    eq('xargs', await run('echo p q | xargs mkdir; ls -d p q; rmdir p q'), 'p  q\n');
    eq('find', await run('find notes'), 'notes\nnotes/ab.txt\nnotes/f.txt\n');
    eq('find -name', await run('find . -name "*.txt" | head -2'), './abc.txt\n./ab.txt\n');
    eq('find -type d', await run('find . -type d'), '.\n./a\n./a/b\n./a/b/c\n./notes\n./projects\n');
    eq('find -iname', await run('find . -iname "AB.TXT"'), './ab.txt\n./notes/ab.txt\n');
    eq('find -empty', await run('find . -empty -type d'), './a/b/c\n');
    eq('find missing', await run('find nope'), "find: 'nope': No such file or directory\n", 1);
    eq('find bad', await run('find . -size 1'), "find: unknown predicate '-size'\n", 1);
    eq('tree', await run('tree a'), 'a\n└── b\n    └── c\n\n2 directories, 0 files\n');
    eq('tree many', await run('tree notes'), 'notes\n├── ab.txt\n└── f.txt\n\n0 directories, 2 files\n');
    eq('echo', await run('echo a  b "c  d"'), 'a b c  d\n');
    eq('echo -n -e', await run('echo -n x; echo -e "\\ty"'), 'x\ty\n');
    eq('echo no -e keeps \\n', await run('echo "a\\nb"'), 'a\\nb\n');
    eq('printf', await run('printf "%s=%d|%5.1f|%-3s|%03d|%%\\n" x 42 3.14159 ab 7'), 'x=42|  3.1|ab |007|%\n');
    eq('printf reuse', await run('printf "%s\\n" a b'), 'a\nb\n');
    eq('seq', await run('seq 3; seq 2 4; seq 0 5 10'), '1\n2\n3\n2\n3\n4\n0\n5\n10\n');
    eq('seq bad', await run('seq x'), "seq: invalid floating point argument: 'x'\n", 1);
    eq('date', await run('date +%Y-%m'), /^\d{4}-\d\d\n$/);
    eq('whoami hostname', await run('whoami; hostname; id'), 'student\nlab\nuid=1000(student) gid=1000(student) groups=1000(student)\n');
    eq('file', await run('file notes ab.txt nope'), "notes:  directory\nab.txt: ASCII text\nnope:   cannot open 'nope' (No such file or directory)\n", 1);
    eq('chmod +x and ./', await run('printf "echo ran\\n" > s.sh; ./s.sh; chmod +x s.sh; ./s.sh; ls -l s.sh | cut -c 1-10'), 'bash: ./s.sh: Permission denied\nran\n-rwxr-xr-x\n');
    eq('chmod 644', await run('chmod 644 s.sh; ./s.sh'), 'bash: ./s.sh: Permission denied\n', 126);
    eq('chmod bad', await run('chmod zz s.sh'), "chmod: invalid mode: 'zz'\n", 1);
    eq('./ missing', await run('./nope'), 'bash: ./nope: No such file or directory\n', 127);
    eq('./ dir', await run('./notes'), 'bash: ./notes: Is a directory\n', 126);
    eq('command not found', await run('frobnicate'), 'bash: frobnicate: command not found\n', 127);
    eq('/bin/ls works', await run('/bin/ls notes'), 'ab.txt  f.txt\n');
    eq('history', await run('history | tail -1'), /^ *\d+  history \| tail -1\n$/);
    eq('which type', await run('which ls cd; echo $?; type cd ls'), '/bin/ls\n1\ncd is a shell builtin\nls is /bin/ls\n');
    eq('man', await run('man ls | head -2'), /^LS\(1\) +User Commands\n\n$/);
    eq('man missing', await run('man frob'), 'No manual entry for frob\n', 16);
    eq('help', await run('help | grep -c .'), /^\d\d\n$/);
    eq('sudo', await run('sudo ls'), 'student is not in the sudoers file.  This incident will be reported.\n', 1);
    eq('git', await run('git status'), /no network/, 1);
    eq('vi', await run('vi s.sh'), /use nano s\.sh/, 127);
    eq('exit at prompt', await run('true; exit'), '(this terminal stays open: close its panel to leave)\n', 0);
  }

  // ---- the shell language
  {
    const { sh, run } = fresh();
    eq('variables', await run('name=Ada; echo "Hi, $name!"; echo ${name}s; echo \'$name\''), 'Hi, Ada!\nAdas\n$name\n');
    eq('unset var is empty', await run('echo "[$nothing]"'), '[]\n');
    eq('env vars', await run('echo $HOME $USER $PWD'), '/home/student student /home/student\n');
    eq('export', await run('export X=1; echo $X; unset X; echo "[$X]"'), '1\n[]\n');
    eq('prefix assignment', await run('A=1 true; echo "[$A]"'), '[]\n');
    eq('status', await run('ls nope 2>/dev/null; echo $?; true; echo $?'), '2\n0\n');
    eq('&& ||', await run('true && echo a; false && echo b; false || echo c; true || echo d'), 'a\nc\n');
    eq('!', await run('! false && echo ok'), 'ok\n');
    eq('; sequence', await run('echo 1; echo 2; echo 3'), '1\n2\n3\n');
    eq('newlines', await run('echo 1\necho 2'), '1\n2\n');
    eq('pipe', await run('printf "c\\nb\\na\\n" | sort | head -1'), 'a\n');
    eq('pipe uses stdin not keyboard', await run('echo x | cat'), 'x\n');
    eq('pipeline status is the last', await run('false | true; echo $?; true | false; echo $?'), '0\n1\n');
    eq('$()', await run('echo "there are $(ls / | wc -l) things"'), 'there are 6 things\n');
    eq('$() nested', await run('echo $(echo $(echo deep))'), 'deep\n');
    eq('backticks', await run('echo `echo bt`'), 'bt\n');
    eq('$(( ))', await run('x=5; echo $((x * 2)) $((x - 10)) $((10 / 3)) $((2 ** 8))'), '10 -5 3 256\n');
    eq('arith division by zero', await run('echo $((1 / 0))'), 'bash: arithmetic: division by 0\n', 2);
    eq('for', await run('for i in 1 2 3; do echo "n=$i"; done'), 'n=1\nn=2\nn=3\n');
    eq('for over glob', await run('touch a.txt b.txt; for f in *.txt; do echo $f; done'), 'a.txt\nb.txt\n');
    eq('for over $()', await run('for i in $(seq 2); do echo $i; done'), '1\n2\n');
    eq('for with braces', await run('for i in {1..3}; do echo -n $i; done; echo'), '123\n');
    eq('while', await run('n=3; while [ $n -gt 0 ]; do echo $n; n=$((n - 1)); done'), '3\n2\n1\n');
    eq('until', await run('n=0; until [ $n -ge 2 ]; do n=$((n + 1)); done; echo $n'), '2\n');
    eq('if', await run('if [ -f a.txt ]; then echo yes; else echo no; fi; if [ -f zz ]; then echo yes; else echo no; fi'), 'yes\nno\n');
    eq('elif', await run('x=5; if [ $x -lt 3 ]; then echo small; elif [ $x -lt 10 ]; then echo medium; else echo big; fi'), 'medium\n');
    eq('test strings', await run('[ abc = abc ] && echo 1; [ abc != abd ] && echo 2; [ -z "" ] && echo 3; [ -n "x" ] && echo 4; test -d /etc && echo 5'), '1\n2\n3\n4\n5\n');
    eq('test numbers', await run('[ 10 -gt 9 ] && echo yes; [ 10 -lt 9 ] || echo no; [ 3 -eq 3 ] && [ 3 -ne 4 ] && echo both'), 'yes\nno\nboth\n');
    eq('test bad', await run('[ a -gt 1 ]'), "bash: [: integer expression expected: 'a'\n", 2);
    eq('test missing ]', await run('[ a = a'), "bash: [: missing `]'\n", 2);
    eq('group', await run('{ echo a; echo b; } | wc -l'), '2\n');
    eq('subshell keeps cwd', await run('(cd /tmp; pwd); pwd'), '/tmp\n/home/student\n');
    eq('for with redirect', await run('for i in 1 2; do echo $i; done > nums.txt; cat nums.txt'), '1\n2\n');
    eq('while read', await run('while read w; do echo "<$w>"; done < nums.txt'), '<1>\n<2>\n');
    eq('read -p', await run('read -p "Name? " n; echo "hi $n"'), 'hi typed\n');
    eq('read from pipe', await run('echo "a b c" | { read x y; echo "$y|$x"; }'), 'b c|a\n');
    eq('script', await run('printf \'#!/bin/bash\\necho "args=$# first=$1 all=$@"\\nexit 3\\n\' > s.sh; bash s.sh p q; echo "got $?"'), 'args=2 first=p all=p q\ngot 3\n');
    eq('script with ./ and args', await run('chmod +x s.sh; ./s.sh z'), 'args=1 first=z all=z\n', 3);
    eq('source keeps variables', await run('echo "SV=set" > v.sh; source v.sh; echo $SV; . v.sh'), 'set\n');
    eq('bash -c', await run('bash -c "echo in; echo line"'), 'in\nline\n');
    eq('bash missing', await run('bash nope.sh'), 'bash: nope.sh: No such file or directory\n', 127);
    eq('script syntax error', await run('echo "echo \\"oops" > bad.sh; bash bad.sh'), /^bad\.sh: unexpected EOF/, 2);
    eq('exit in script does not stop the line', await run('echo "exit 7" > e.sh; bash e.sh; echo after $?'), 'after 7\n');
    eq('__proto__ as a file name', await run('mkdir __proto__; echo x > __proto__/constructor; cat __proto__/constructor; ls -d __proto__; rm -r __proto__'), 'x\n__proto__\n');
    eq('loop limit', await run('while true; do :; done'), /stopped: more than \d+ commands/, 1);
    eq('loop limit in script', await run('printf "while true; do\\n  :\\ndone\\n" > inf.sh; bash inf.sh'), /stopped: more than/, 1);
    eq('output limit', await run('yes 2>/dev/null; x=a; while true; do x="$x$x$x$x"; echo $x; done > big.txt'), /stopped: the command produced more output/, 1);
    eq('big file limit', await run('ls -l big.txt | cut -c 1-1'), '-\n');
    eq('too many files', await run('mkdir many; cd many; for i in $(seq 600); do touch f$i; done; cd ..; ls many | wc -l'), /No space|Too many files/, undefined);
    check('file count capped', (await run('ls many | wc -l')).out <= SHELL.LIMITS.files + '\n', true);
    eq('syntax error status', await run('echo "unclosed'), "bash: unexpected EOF while looking for matching `\"'\n", 2);
    eq('cancel', await (async () => { const p = run('sleep 3; echo after'); sh.cancel(); return p; })(), '^C\n', 130);
    eq('history dedupes', await run('history | tail -2 | head -1'), /sleep 3; echo after/);
    eq('control char in input', await run('echo a\u0000b'), 'ab\n');
    eq('__proto__ as a variable name', await run('__proto__=1; echo "[$__proto__]"; constructor=2; echo $constructor'), '[1]\n2\n');
    eq('tab completion commands', { out: sh.complete('gre').items.join(','), exit: 0 }, 'grep ');
    eq('tab completion files', { out: sh.complete('cat a.').items.join(','), exit: 0 }, 'a.txt ');
    eq('tab completion dirs', { out: sh.complete('cd ma').items.join(','), exit: 0 }, 'many/');
    eq('tab completion after pipe', { out: sh.complete('ls | wc').items.join(','), exit: 0 }, 'wc ');
    eq('tab completion in a dir', { out: sh.complete('ls many/f1').items.length > 10, exit: 0 }, true);
    check('tab completion: cd lists no files', sh.complete('cd ').items.every((i) => i.endsWith('/')), true);
    eq('tab completion: ..', { out: sh.complete('cd ..').items.join(','), exit: 0 }, '../');
    await run('rm -r many; touch "my file.txt"; mkdir "odd dir"');   // (many held the 500 files of the cap test)
    eq('tab completion escapes spaces', { out: sh.complete('cat my').items.join(','), exit: 0 }, 'my\\ file.txt ');
    eq('tab completion inside quotes', { out: sh.complete('cat "my').items.join(','), exit: 0 }, '"my file.txt" ');
    eq('tab completion after an escaped space', { out: sh.complete('cat my\\ fi').items.join(','), exit: 0 }, 'my\\ file.txt ');
    eq('tab completion display is bare', { out: sh.complete('ls od').display.join(','), exit: 0 }, 'odd dir/');
    await run('rm "my file.txt"; rmdir "odd dir"');
  }

  // ---- programs, through the hooks
  {
    const { sh, run, asks } = fresh({ nano: async (p, text) => text + 'edited\n', edit: (abs) => 'opened ' + abs, setup: (n) => n === 'lesson2' ? 'made files' : null });
    eq('python', await run('echo "print(1)" > h.py; python h.py; python3 h.py a b'), 'python:print(1)\npython:print(1) a,b\n', 0);
    eq('python missing', await run('python nope.py'), "python: can't open file '/home/student/nope.py': [Errno 2] No such file or directory\n", 2);
    eq('python no args', await run('python'), /interactive Python shell is not available/, 2);
    eq('python < file', await run('echo 5 > in.txt; python h.py < in.txt'), 'python:print(1)<"5\\n"\n');
    eq('python | pipe', await run('echo 7 | python h.py'), 'python:print(1)<"7\\n"\n');
    eq('python > file', await run('python h.py > out.txt; cat out.txt'), 'python:print(1)\n');
    eq('python error status', await run('echo boom > b.py; python b.py; echo $?'), 'python:boom\nError: boom\n1\n');
    eq('python shebang', await run('printf "#!/usr/bin/env python3\\nprint(2)\\n" > r.py; chmod +x r.py; ./r.py'), 'python:#!/usr/bin/env python3\nprint(2)\n');
    eq('javac + java', await run('echo "public class Main { }" > Main.java; javac Main.java; ls Main.class; java Main'), 'Main.class\njava:public class Main { }\n', 0);
    eq('java without class', await run('rm Main.class; java Main'), 'Error: Could not find or load main class Main\nCaused by: java.lang.ClassNotFoundException: Main\n(there is a Main.java: compile it first with javac Main.java)\n', 1);
    eq('java source launcher', await run('java Main.java'), 'java:public class Main { }\n');
    eq('javac wrong name', await run('echo "public class Foo { }" > Main.java; javac Main.java'), 'Main.java:1: error: class Foo is public, should be declared in a file named Foo.java\n1 error\n', 1);
    eq('javac error', await run('echo "class Main { bad }" > Main.java; javac Main.java; ls Main.class'), "Main.java:1:1: error: bad\nls: cannot access 'Main.class': No such file or directory\n");
    eq('javac missing', await run('javac Nope.java'), 'error: file not found: Nope.java\nUsage: javac <options> <source files>\n', 1);
    eq('java < stdin', await run('echo "class Main { Scanner }" > Main.java; javac Main.java && java Main < in.txt'), 'java:class Main { Scanner }<"5\\n"\n');
    eq('java reads keyboard', await run('java Main'), /reads input.*\njava:class Main \{ Scanner \}<"typed\\n/);
    eq('g++', await run('echo "int main() { return 0; }" > m.cpp; g++ m.cpp -o m; ./m; ls -F m'), 'cpp:int main() { return 0; }\nm*\n', 0);
    eq('g++ default name', await run('g++ m.cpp; ./a.out'), 'cpp:int main() { return 0; }\n');
    eq('g++ -std', await run('g++ -std=c++17 -Wall m.cpp -o m17 && ./m17'), 'cpp:int main() { return 0; }\n');
    eq('g++ error', await run('echo "int main() { bad }" > e.cpp; g++ e.cpp -o e; ls e'), "e.cpp:1:1: error: bad\nls: cannot access 'e': No such file or directory\n");
    eq('g++ no files', await run('g++'), 'g++: fatal error: no input files\ncompilation terminated.\n', 1);
    eq('g++ missing', await run('g++ nope.cpp'), 'g++: error: nope.cpp: No such file or directory\ng++: fatal error: no input files\ncompilation terminated.\n', 1);
    eq('binary is not text', await run('file m; cat m | cut -c 2-4'), 'm: ELF 64-bit LSB executable, x86-64\nELF\n');
    eq('cannot nano a binary', await run('nano m'), 'nano: m is a compiled program, not text\n', 1);
    eq('scheme', await run('echo "(display 1)" > f.scm; scheme f.scm'), 'scheme:(display 1)\n');
    eq('nano', await run('nano note.txt; cat note.txt'), 'edited\n');
    eq('nano dir', await run('mkdir dd; nano dd'), 'nano: dd: Is a directory\n', 1);
    const { run: runW } = fresh({ nano: async (p, text, write) => { write(text + 'first\n'); write(text + 'first\nsecond\n'); return null; } });
    eq('nano saves through write() as it goes', await runW('echo start > w.txt; nano w.txt; cat w.txt'), 'start\nfirst\nsecond\n');
    let writeErr = null; const { run: runE } = fresh({ nano: async (p, text, write) => { writeErr = write('x'.repeat(300000)); return null; } });
    eq('nano: a write that fails is reported to the editor, not written', await runE('nano big.txt; ls big.txt'), "ls: cannot access 'big.txt': No such file or directory\n", 2); check('nano write error text', writeErr, 'File too large');
    eq('edit', await run('edit note.txt'), 'opened /home/student/note.txt\n');
    eq('setup', await run('setup lesson2; setup nope'), 'made files\nsetup: there is no "nope" to set up\n', 1);
    const { run: run2 } = fresh();
    eq('no hooks: nano', await run2('nano x'), 'nano: no editor is available here\n', 1);
    eq('no hooks: setup', await run2('setup x'), 'setup: nothing to set up here\n', 1);
  }

  // ---- saving and reloading a session's work
  {
    const { fs, run } = fresh();
    await run('mkdir -p p/q; echo data > p/q/d.txt; cd p');
    const json = JSON.parse(JSON.stringify(fs.toJSON()));
    const fs2 = SHELL.makeFS(json, { now: () => T0 });
    const sh2 = SHELL.makeShell({ fs: fs2 });
    let out = ''; await sh2.exec('pwd; cat q/d.txt', { out: (s) => { out += s; }, err: (s) => { out += s; } });
    check('reloaded session', out, '/home/student/p\ndata\n');
  }

  console.log(bad ? bad + ' shell test(s) failed' : 'shell tests passed');
  process.exit(bad ? 1 : 0);
})().catch((e) => { console.log(e.stack); process.exit(1); });
